#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AI_skill_phoebe_bot_movement

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AI_skill_phoebe_bot_movement.AI_skill_phoebe_bot_movement_C
// 0x0000 (0x04C8 - 0x04C8)
class UAI_skill_phoebe_bot_movement_C final : public UFortAthenaAIBotMovementSkillSet
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AI_skill_phoebe_bot_movement_C">();
	}
	static class UAI_skill_phoebe_bot_movement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAI_skill_phoebe_bot_movement_C>();
	}
};
static_assert(alignof(UAI_skill_phoebe_bot_movement_C) == 0x000008, "Wrong alignment on UAI_skill_phoebe_bot_movement_C");
static_assert(sizeof(UAI_skill_phoebe_bot_movement_C) == 0x0004C8, "Wrong size on UAI_skill_phoebe_bot_movement_C");

}

