#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_Fac_Pipe_T_02_Child_OilRig

#include "Basic.hpp"

#include "Apollo_Fac_Pipe_T_02_Child_OilRig_classes.hpp"
#include "Apollo_Fac_Pipe_T_02_Child_OilRig_parameters.hpp"


namespace SDK
{

// Function Apollo_Fac_Pipe_T_02_Child_OilRig.Apollo_Fac_Pipe_T_02_Child_OilRig_C.ExecuteUbergraph_Apollo_Fac_Pipe_T_02_Child_OilRig
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AApollo_Fac_Pipe_T_02_Child_OilRig_C::ExecuteUbergraph_Apollo_Fac_Pipe_T_02_Child_OilRig(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Apollo_Fac_Pipe_T_02_Child_OilRig_C", "ExecuteUbergraph_Apollo_Fac_Pipe_T_02_Child_OilRig");

	Params::Apollo_Fac_Pipe_T_02_Child_OilRig_C_ExecuteUbergraph_Apollo_Fac_Pipe_T_02_Child_OilRig Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Apollo_Fac_Pipe_T_02_Child_OilRig.Apollo_Fac_Pipe_T_02_Child_OilRig_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AApollo_Fac_Pipe_T_02_Child_OilRig_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Apollo_Fac_Pipe_T_02_Child_OilRig_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

