#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Apollo_SJI_8x16_Mansion_c_e89f1a22

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Apollo_SJI_8x16_Mansion_c_e89f1a22.Apollo_SJI_8x16_Mansion_c_C
// 0x0000 (0x0238 - 0x0238)
class AApollo_SJI_8x16_Mansion_c_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Apollo_SJI_8x16_Mansion_c_C">();
	}
	static class AApollo_SJI_8x16_Mansion_c_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AApollo_SJI_8x16_Mansion_c_C>();
	}
};
static_assert(alignof(AApollo_SJI_8x16_Mansion_c_C) == 0x000008, "Wrong alignment on AApollo_SJI_8x16_Mansion_c_C");
static_assert(sizeof(AApollo_SJI_8x16_Mansion_c_C) == 0x000238, "Wrong size on AApollo_SJI_8x16_Mansion_c_C");

}

