#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_Prop_Office_WaterCooler_01

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_Prop_Office_WaterCooler_01.Athena_Prop_Office_WaterCooler_01_C
// 0x0000 (0x0BC0 - 0x0BC0)
class Athena_Prop_Office_WaterCooler_01::AAthena_Prop_Office_WaterCooler_01_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass Athena_Prop_Office_WaterCooler_01.Athena_Prop_Office_WaterCooler_01_C", true, "Athena_Prop_Office_WaterCooler_01_C">();
	}
	static class Athena_Prop_Office_WaterCooler_01::AAthena_Prop_Office_WaterCooler_01_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Athena_Prop_Office_WaterCooler_01::AAthena_Prop_Office_WaterCooler_01_C>();
	}
};
static_assert(alignof(Athena_Prop_Office_WaterCooler_01::AAthena_Prop_Office_WaterCooler_01_C) == 0x000008, "Wrong alignment on Athena_Prop_Office_WaterCooler_01::AAthena_Prop_Office_WaterCooler_01_C");
static_assert(sizeof(Athena_Prop_Office_WaterCooler_01::AAthena_Prop_Office_WaterCooler_01_C) == 0x000BC0, "Wrong size on Athena_Prop_Office_WaterCooler_01::AAthena_Prop_Office_WaterCooler_01_C");

}

