#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_HappyGhost_Athena

#include "Basic.hpp"


namespace SDK::Params
{

// Function B_HappyGhost_Athena.B_HappyGhost_Athena_C.ExecuteUbergraph_B_HappyGhost_Athena
// 0x0004 (0x0004 - 0x0000)
struct B_HappyGhost_Athena_C_ExecuteUbergraph_B_HappyGhost_Athena final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(B_HappyGhost_Athena_C_ExecuteUbergraph_B_HappyGhost_Athena) == 0x000004, "Wrong alignment on B_HappyGhost_Athena_C_ExecuteUbergraph_B_HappyGhost_Athena");
static_assert(sizeof(B_HappyGhost_Athena_C_ExecuteUbergraph_B_HappyGhost_Athena) == 0x000004, "Wrong size on B_HappyGhost_Athena_C_ExecuteUbergraph_B_HappyGhost_Athena");
static_assert(offsetof(B_HappyGhost_Athena_C_ExecuteUbergraph_B_HappyGhost_Athena, EntryPoint) == 0x000000, "Member 'B_HappyGhost_Athena_C_ExecuteUbergraph_B_HappyGhost_Athena::EntryPoint' has a wrong offset!");

}

