#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_Quest_Ring

#include "Basic.hpp"

#include "BGA_Quest_Ring_classes.hpp"
#include "BGA_Quest_Ring_parameters.hpp"


namespace SDK
{

// Function BGA_Quest_Ring.BGA_Quest_Ring_C.ExecuteUbergraph_BGA_Quest_Ring
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Quest_Ring_C::ExecuteUbergraph_BGA_Quest_Ring(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Quest_Ring_C", "ExecuteUbergraph_BGA_Quest_Ring");

	Params::BGA_Quest_Ring_C_ExecuteUbergraph_BGA_Quest_Ring Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Quest_Ring.BGA_Quest_Ring_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABGA_Quest_Ring_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Quest_Ring_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Quest_Ring.BGA_Quest_Ring_C.BndEvt__QuestComponent_K2Node_ComponentBoundEvent_4_SimpleQuestComponentDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AFortPlayerController*            PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Quest_Ring_C::BndEvt__QuestComponent_K2Node_ComponentBoundEvent_4_SimpleQuestComponentDelegate__DelegateSignature(class AFortPlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Quest_Ring_C", "BndEvt__QuestComponent_K2Node_ComponentBoundEvent_4_SimpleQuestComponentDelegate__DelegateSignature");

	Params::BGA_Quest_Ring_C_BndEvt__QuestComponent_K2Node_ComponentBoundEvent_4_SimpleQuestComponentDelegate__DelegateSignature Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Quest_Ring.BGA_Quest_Ring_C.BndEvt__QuestComponent_K2Node_ComponentBoundEvent_2_SimpleQuestComponentDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AFortPlayerController*            PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Quest_Ring_C::BndEvt__QuestComponent_K2Node_ComponentBoundEvent_2_SimpleQuestComponentDelegate__DelegateSignature(class AFortPlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Quest_Ring_C", "BndEvt__QuestComponent_K2Node_ComponentBoundEvent_2_SimpleQuestComponentDelegate__DelegateSignature");

	Params::BGA_Quest_Ring_C_BndEvt__QuestComponent_K2Node_ComponentBoundEvent_2_SimpleQuestComponentDelegate__DelegateSignature Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Quest_Ring.BGA_Quest_Ring_C.BndEvt__QuestComponent_K2Node_ComponentBoundEvent_1_SimpleQuestComponentDelegate__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class AFortPlayerController*            PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Quest_Ring_C::BndEvt__QuestComponent_K2Node_ComponentBoundEvent_1_SimpleQuestComponentDelegate__DelegateSignature(class AFortPlayerController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Quest_Ring_C", "BndEvt__QuestComponent_K2Node_ComponentBoundEvent_1_SimpleQuestComponentDelegate__DelegateSignature");

	Params::BGA_Quest_Ring_C_BndEvt__QuestComponent_K2Node_ComponentBoundEvent_1_SimpleQuestComponentDelegate__DelegateSignature Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Quest_Ring.BGA_Quest_Ring_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Quest_Ring_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Quest_Ring_C", "ReceiveActorBeginOverlap");

	Params::BGA_Quest_Ring_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Quest_Ring.BGA_Quest_Ring_C.UpdateLoopingAudio
// (Public, BlueprintCallable, BlueprintEvent)

void ABGA_Quest_Ring_C::UpdateLoopingAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Quest_Ring_C", "UpdateLoopingAudio");

	UObject::ProcessEvent(Func, nullptr);
}

}

