#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BridgeSupport_01_Top

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BridgeSupport_01_Top.BridgeSupport_01_Top_C
// 0x0000 (0x0CD8 - 0x0CD8)
class ABridgeSupport_01_Top_C final : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BridgeSupport_01_Top_C">();
	}
	static class ABridgeSupport_01_Top_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABridgeSupport_01_Top_C>();
	}
};
static_assert(alignof(ABridgeSupport_01_Top_C) == 0x000008, "Wrong alignment on ABridgeSupport_01_Top_C");
static_assert(sizeof(ABridgeSupport_01_Top_C) == 0x000CD8, "Wrong size on ABridgeSupport_01_Top_C");

}

