#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Fence_Rural

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Fence_Rural.Fence_Rural_C
// 0x0000 (0x0CD8 - 0x0CD8)
class AFence_Rural_C : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Fence_Rural_C">();
	}
	static class AFence_Rural_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFence_Rural_C>();
	}
};
static_assert(alignof(AFence_Rural_C) == 0x000008, "Wrong alignment on AFence_Rural_C");
static_assert(sizeof(AFence_Rural_C) == 0x000CD8, "Wrong size on AFence_Rural_C");

}

