#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Frontend_BP13_Room_A_Scripting

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Frontend_BP13_Room_A_Scripting.Frontend_BP13_Room_A_Scripting_C
// 0x0000 (0x0238 - 0x0238)
class AFrontend_BP13_Room_A_Scripting_C final : public AFortLevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Frontend_BP13_Room_A_Scripting_C">();
	}
	static class AFrontend_BP13_Room_A_Scripting_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFrontend_BP13_Room_A_Scripting_C>();
	}
};
static_assert(alignof(AFrontend_BP13_Room_A_Scripting_C) == 0x000008, "Wrong alignment on AFrontend_BP13_Room_A_Scripting_C");
static_assert(sizeof(AFrontend_BP13_Room_A_Scripting_C) == 0x000238, "Wrong size on AFrontend_BP13_Room_A_Scripting_C");

}

