#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_HidingProp_DestroyStructure

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_HidingProp_DestroyStructure.GE_HidingProp_DestroyStructure_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_HidingProp_DestroyStructure_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_HidingProp_DestroyStructure_C">();
	}
	static class UGE_HidingProp_DestroyStructure_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_HidingProp_DestroyStructure_C>();
	}
};
static_assert(alignof(UGE_HidingProp_DestroyStructure_C) == 0x000008, "Wrong alignment on UGE_HidingProp_DestroyStructure_C");
static_assert(sizeof(UGE_HidingProp_DestroyStructure_C) == 0x0007B8, "Wrong size on UGE_HidingProp_DestroyStructure_C");

}

