#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Quest_Search_SupplyDrop_AfterLanding

#include "Basic.hpp"

#include "GE_Quest_TagCarrier_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Quest_Search_SupplyDrop_AfterLanding.GE_Quest_Search_SupplyDrop_AfterLanding_C
// 0x0000 (0x07B8 - 0x07B8)
class UGE_Quest_Search_SupplyDrop_AfterLanding_C final : public UGE_Quest_TagCarrier_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Quest_Search_SupplyDrop_AfterLanding_C">();
	}
	static class UGE_Quest_Search_SupplyDrop_AfterLanding_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Quest_Search_SupplyDrop_AfterLanding_C>();
	}
};
static_assert(alignof(UGE_Quest_Search_SupplyDrop_AfterLanding_C) == 0x000008, "Wrong alignment on UGE_Quest_Search_SupplyDrop_AfterLanding_C");
static_assert(sizeof(UGE_Quest_Search_SupplyDrop_AfterLanding_C) == 0x0007B8, "Wrong size on UGE_Quest_Search_SupplyDrop_AfterLanding_C");

}

