#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LatencyContainer

#include "Basic.hpp"

#include "LatencyContainer_classes.hpp"
#include "LatencyContainer_parameters.hpp"


namespace SDK
{

// Function LatencyContainer.LatencyContainer_C.ExecuteUbergraph_LatencyContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULatencyContainer_C::ExecuteUbergraph_LatencyContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LatencyContainer_C", "ExecuteUbergraph_LatencyContainer");

	Params::LatencyContainer_C_ExecuteUbergraph_LatencyContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LatencyContainer.LatencyContainer_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULatencyContainer_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LatencyContainer_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LatencyContainer.LatencyContainer_C.OnVisibilitySetEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// ESlateVisibility                        InVisibility                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULatencyContainer_C::OnVisibilitySetEvent(ESlateVisibility InVisibility)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LatencyContainer_C", "OnVisibilitySetEvent");

	Params::LatencyContainer_C_OnVisibilitySetEvent Parms{};

	Parms.InVisibility = InVisibility;

	UObject::ProcessEvent(Func, &Parms);
}

}

