#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Mansion_DeerHead

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Mansion_DeerHead.Mansion_DeerHead_C
// 0x0000 (0x0BC0 - 0x0BC0)
class AMansion_DeerHead_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Mansion_DeerHead_C">();
	}
	static class AMansion_DeerHead_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMansion_DeerHead_C>();
	}
};
static_assert(alignof(AMansion_DeerHead_C) == 0x000008, "Wrong alignment on AMansion_DeerHead_C");
static_assert(sizeof(AMansion_DeerHead_C) == 0x000BC0, "Wrong size on AMansion_DeerHead_C");

}

