#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Neo_SkyScraper_Trim_Crn

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Neo_SkyScraper_Trim_Crn.Neo_SkyScraper_Trim_Crn_C
// 0x0000 (0x0B70 - 0x0B70)
class ANeo_SkyScraper_Trim_Crn_C final : public ABuildingPropCorner
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Neo_SkyScraper_Trim_Crn_C">();
	}
	static class ANeo_SkyScraper_Trim_Crn_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ANeo_SkyScraper_Trim_Crn_C>();
	}
};
static_assert(alignof(ANeo_SkyScraper_Trim_Crn_C) == 0x000008, "Wrong alignment on ANeo_SkyScraper_Trim_Crn_C");
static_assert(sizeof(ANeo_SkyScraper_Trim_Crn_C) == 0x000B70, "Wrong size on ANeo_SkyScraper_Trim_Crn_C");

}

