#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OilRig_Platform_Wall_01_Window_02

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OilRig_Platform_Wall_01_Window_02.OilRig_Platform_Wall_01_Window_02_C
// 0x0000 (0x0CD8 - 0x0CD8)
class AOilRig_Platform_Wall_01_Window_02_C final : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"OilRig_Platform_Wall_01_Window_02_C">();
	}
	static class AOilRig_Platform_Wall_01_Window_02_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOilRig_Platform_Wall_01_Window_02_C>();
	}
};
static_assert(alignof(AOilRig_Platform_Wall_01_Window_02_C) == 0x000008, "Wrong alignment on AOilRig_Platform_Wall_01_Window_02_C");
static_assert(sizeof(AOilRig_Platform_Wall_01_Window_02_C) == 0x000CD8, "Wrong size on AOilRig_Platform_Wall_01_Window_02_C");

}

