#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Phoebe_HandleFocusing_IgnoreThreat

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Phoebe_HandleFocusing_IgnoreThreat.Phoebe_HandleFocusing_IgnoreThreat_C
// 0x0000 (0x00F0 - 0x00F0)
class UPhoebe_HandleFocusing_IgnoreThreat_C final : public UFortAthenaAIBotEvaluator_HandleFocusing
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Phoebe_HandleFocusing_IgnoreThreat_C">();
	}
	static class UPhoebe_HandleFocusing_IgnoreThreat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPhoebe_HandleFocusing_IgnoreThreat_C>();
	}
};
static_assert(alignof(UPhoebe_HandleFocusing_IgnoreThreat_C) == 0x000008, "Wrong alignment on UPhoebe_HandleFocusing_IgnoreThreat_C");
static_assert(sizeof(UPhoebe_HandleFocusing_IgnoreThreat_C) == 0x0000F0, "Wrong size on UPhoebe_HandleFocusing_IgnoreThreat_C");

}

