#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PirateShip_Rigging

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PirateShip_Rigging.PirateShip_Rigging_C
// 0x0000 (0x0BC0 - 0x0BC0)
class APirateShip_Rigging_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PirateShip_Rigging_C">();
	}
	static class APirateShip_Rigging_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APirateShip_Rigging_C>();
	}
};
static_assert(alignof(APirateShip_Rigging_C) == 0x000008, "Wrong alignment on APirateShip_Rigging_C");
static_assert(sizeof(APirateShip_Rigging_C) == 0x000BC0, "Wrong size on APirateShip_Rigging_C");

}

