#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PowerPlant_Light03

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PowerPlant_Light03.PowerPlant_Light03_C
// 0x0000 (0x0BC0 - 0x0BC0)
class APowerPlant_Light03_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PowerPlant_Light03_C">();
	}
	static class APowerPlant_Light03_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APowerPlant_Light03_C>();
	}
};
static_assert(alignof(APowerPlant_Light03_C) == 0x000008, "Wrong alignment on APowerPlant_Light03_C");
static_assert(sizeof(APowerPlant_Light03_C) == 0x000BC0, "Wrong size on APowerPlant_Light03_C");

}

