#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prj_Athena_HappyGhost

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Prj_Athena_HappyGhost.Prj_Athena_HappyGhost_C.ExecuteUbergraph_Prj_Athena_HappyGhost
// 0x0530 (0x0530 - 0x0000)
struct Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7BCA[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_OtherActor_1;                         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPickup*                            K2Node_DynamicCast_AsFort_Pickup;                  // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BCB[0x6];                                     // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class ABGA_Athena_FlopperSpawn_World_C*       K2Node_DynamicCast_AsBGA_Athena_Flopper_Spawn_World; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BCC[0x5];                                     // 0x002B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0038(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0044(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BCD[0x3];                                     // 0x0051(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_2;        // 0x0054(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_3;        // 0x0060(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x006C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0078(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7BCE[0x4];                                     // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPrimitiveComponent*                    K2Node_Event_MyComp;                               // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_Other;                                // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_Event_OtherComp_1;                          // 0x0098(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bSelfMoved;                           // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BCF[0x3];                                     // 0x00A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                K2Node_Event_HitLocation;                          // 0x00A4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_HitNormal;                            // 0x00B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Event_NormalImpulse;                        // 0x00BC(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_Hit;                                  // 0x00C8(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	uint8                                         Pad_7BD0[0x4];                                     // 0x0154(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IGameplayTagAssetInterface> K2Node_DynamicCast_AsGameplay_Tag_Asset_Interface; // 0x0158(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD1[0x7];                                     // 0x0169(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  K2Node_DynamicCast_AsPawn;                         // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0178(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0179(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x017A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD2[0x5];                                     // 0x017B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class ABuildingActor*                         K2Node_DynamicCast_AsBuilding_Actor;               // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0189(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x018A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x018B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x018C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD3[0x3];                                     // 0x018D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_1;              // 0x0190(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD4[0x7];                                     // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_HappyGhost_Athena_C*                 K2Node_DynamicCast_AsB_Happy_Ghost_Athena;         // 0x01B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD5[0x7];                                     // 0x01B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x01C0(0x0010)(ConstParm, ReferenceParm, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_OtherActor;                           // 0x01D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    K2Node_Event_OtherComp;                            // 0x01D8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             K2Node_Event_HitResult;                            // 0x01E0(0x008C)(ConstParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          K2Node_Event_bIsOverlap;                           // 0x026C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD6[0x3];                                     // 0x026D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0270(0x008C)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x02FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x02FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x02FE(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD7[0x1];                                     // 0x02FF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x0300(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0304(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0308(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0314(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0320(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x032C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0338(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0348(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0350(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0358(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x035C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0360(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x036C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortWaterBodyActor*                    K2Node_DynamicCast_AsFort_Water_Body_Actor;        // 0x0378(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_7;                     // 0x0380(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD8[0x3];                                     // 0x0381(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterPlaneLocation;   // 0x0384(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterPlaneNormal;     // 0x0390(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterSurfacePosition; // 0x039C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetWaterSurfaceInfo_WaterDepth;           // 0x03A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetWaterSurfaceInfo_WaterBodyIdx;         // 0x03AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetWaterSurfaceInfo_WaterVelocity;        // 0x03B0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x03BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x03C0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetLastWaterSurfaceInfo_WaterPlaneLocation; // 0x03C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetLastWaterSurfaceInfo_WaterPlaneNormal; // 0x03D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetLastWaterSurfaceInfo_WaterSurfacePosition; // 0x03E0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetLastWaterSurfaceInfo_WaterDepth;       // 0x03EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetLastWaterSurfaceInfo_WaterBodyIdx;     // 0x03F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetLastWaterSurfaceInfo_WaterVelocity;    // 0x03F4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue_1;            // 0x0400(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x0404(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bBlockingHit_1;            // 0x0410(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap_1;         // 0x0411(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BD9[0x2];                                     // 0x0412(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time_1;                    // 0x0414(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance_1;                // 0x0418(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Location_1;                // 0x041C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint_1;             // 0x0428(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal_1;                  // 0x0434(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal_1;            // 0x0440(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7BDA[0x4];                                     // 0x044C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat_1;                 // 0x0450(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor_1;                // 0x0458(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent_1;            // 0x0460(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName_1;             // 0x0468(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem_1;                 // 0x0470(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex_1;               // 0x0474(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceStart_1;              // 0x0478(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd_1;                // 0x0484(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue_1;     // 0x0490(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsServer_ReturnValue_1;                   // 0x0498(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0499(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x049A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BDB[0x5];                                     // 0x049B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPickup*                            K2Node_CustomEvent_FortPickup;                     // 0x04A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetSquaredDistanceTo_ReturnValue;         // 0x04A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7BDC[0x4];                                     // 0x04AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetAttachParentActor_ReturnValue;         // 0x04B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_FloatFloat_ReturnValue;         // 0x04B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x04B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x04BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x04BB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue_2;                   // 0x04BC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BDD[0x3];                                     // 0x04BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_2;              // 0x04C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetSquaredDistanceTo_ReturnValue_1;       // 0x04C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_FloatFloat_ReturnValue;      // 0x04CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BDE[0x3];                                     // 0x04CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_4;        // 0x04D0(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x04DC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BDF[0x3];                                     // 0x04DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x04E0(0x0030)(IsPlainOldData, NoDestructor)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0510(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAnyMatchingGameplayTags_ReturnValue;   // 0x0518(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BE0[0x7];                                     // 0x0519(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AB_Athena_HappyGhost_Wire_C*            CallFunc_FinishSpawningActor_ReturnValue;          // 0x0520(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x0528(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue_3;                   // 0x0529(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x052A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsServer_ReturnValue_4;                   // 0x052B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasInfiniteAmmo_ReturnValue;              // 0x052C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost) == 0x000010, "Wrong alignment on Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost");
static_assert(sizeof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost) == 0x000530, "Wrong size on Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, EntryPoint) == 0x000000, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::EntryPoint' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_OtherActor_1) == 0x000008, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_OtherActor_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsFort_Pickup) == 0x000010, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsFort_Pickup' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsValid_ReturnValue) == 0x000019, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsBGA_Athena_Flopper_Spawn_World) == 0x000020, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsBGA_Athena_Flopper_Spawn_World' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess_1) == 0x000028, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsValid_ReturnValue_1) == 0x000029, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, Temp_bool_IsClosed_Variable) == 0x00002A, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetInstigator_ReturnValue) == 0x000030, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetInstigator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000038, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000044, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsServer_ReturnValue) == 0x000050, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_K2_GetActorLocation_ReturnValue_2) == 0x000054, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_K2_GetActorLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_K2_GetActorLocation_ReturnValue_3) == 0x000060, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_K2_GetActorLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_Subtract_VectorVector_ReturnValue) == 0x00006C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_Add_VectorVector_ReturnValue) == 0x000078, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_MyComp) == 0x000088, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_MyComp' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_Other) == 0x000090, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_Other' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_OtherComp_1) == 0x000098, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_OtherComp_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_bSelfMoved) == 0x0000A0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_bSelfMoved' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_HitLocation) == 0x0000A4, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_HitLocation' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_HitNormal) == 0x0000B0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_HitNormal' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_NormalImpulse) == 0x0000BC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_NormalImpulse' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_Hit) == 0x0000C8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_Hit' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsGameplay_Tag_Asset_Interface) == 0x000158, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsGameplay_Tag_Asset_Interface' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess_2) == 0x000168, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsPawn) == 0x000170, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsPawn' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess_3) == 0x000178, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_Not_PreBool_ReturnValue) == 0x000179, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsValid_ReturnValue_2) == 0x00017A, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsBuilding_Actor) == 0x000180, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsBuilding_Actor' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess_4) == 0x000188, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess_4' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BooleanAND_ReturnValue) == 0x000189, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsValid_ReturnValue_3) == 0x00018A, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BooleanAND_ReturnValue_1) == 0x00018B, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsValid_ReturnValue_4) == 0x00018C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetInstigator_ReturnValue_1) == 0x000190, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetInstigator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetOwner_ReturnValue) == 0x000198, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetOwner_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x0001A0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess_5) == 0x0001A8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess_5' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsB_Happy_Ghost_Athena) == 0x0001B0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsB_Happy_Ghost_Athena' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess_6) == 0x0001B8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess_6' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, Temp_object_Variable) == 0x0001C0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_OtherActor) == 0x0001D0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_OtherActor' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_OtherComp) == 0x0001D8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_OtherComp' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_HitResult) == 0x0001E0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_HitResult' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_Event_bIsOverlap) == 0x00026C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_Event_bIsOverlap' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_LineTraceSingle_OutHit) == 0x000270, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_LineTraceSingle_ReturnValue) == 0x0002FC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_bBlockingHit) == 0x0002FD, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_bInitialOverlap) == 0x0002FE, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Time) == 0x000300, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Distance) == 0x000304, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Location) == 0x000308, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_ImpactPoint) == 0x000314, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Normal) == 0x000320, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_ImpactNormal) == 0x00032C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_PhysMat) == 0x000338, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitActor) == 0x000340, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitComponent) == 0x000348, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitBoneName) == 0x000350, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitItem) == 0x000358, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_FaceIndex) == 0x00035C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_TraceStart) == 0x000360, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_TraceEnd) == 0x00036C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_AsFort_Water_Body_Actor) == 0x000378, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_AsFort_Water_Body_Actor' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_DynamicCast_bSuccess_7) == 0x000380, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_DynamicCast_bSuccess_7' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetWaterSurfaceInfo_WaterPlaneLocation) == 0x000384, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetWaterSurfaceInfo_WaterPlaneLocation' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetWaterSurfaceInfo_WaterPlaneNormal) == 0x000390, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetWaterSurfaceInfo_WaterPlaneNormal' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetWaterSurfaceInfo_WaterSurfacePosition) == 0x00039C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetWaterSurfaceInfo_WaterSurfacePosition' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetWaterSurfaceInfo_WaterDepth) == 0x0003A8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetWaterSurfaceInfo_WaterDepth' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetWaterSurfaceInfo_WaterBodyIdx) == 0x0003AC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetWaterSurfaceInfo_WaterBodyIdx' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetWaterSurfaceInfo_WaterVelocity) == 0x0003B0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetWaterSurfaceInfo_WaterVelocity' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_Conv_IntToFloat_ReturnValue) == 0x0003BC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_SpawnEmitterAtLocation_ReturnValue) == 0x0003C0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_SpawnEmitterAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetLastWaterSurfaceInfo_WaterPlaneLocation) == 0x0003C8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetLastWaterSurfaceInfo_WaterPlaneLocation' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetLastWaterSurfaceInfo_WaterPlaneNormal) == 0x0003D4, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetLastWaterSurfaceInfo_WaterPlaneNormal' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetLastWaterSurfaceInfo_WaterSurfacePosition) == 0x0003E0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetLastWaterSurfaceInfo_WaterSurfacePosition' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetLastWaterSurfaceInfo_WaterDepth) == 0x0003EC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetLastWaterSurfaceInfo_WaterDepth' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetLastWaterSurfaceInfo_WaterBodyIdx) == 0x0003F0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetLastWaterSurfaceInfo_WaterBodyIdx' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetLastWaterSurfaceInfo_WaterVelocity) == 0x0003F4, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetLastWaterSurfaceInfo_WaterVelocity' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_Conv_IntToFloat_ReturnValue_1) == 0x000400, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_Conv_IntToFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x000404, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_bBlockingHit_1) == 0x000410, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_bBlockingHit_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_bInitialOverlap_1) == 0x000411, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_bInitialOverlap_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Time_1) == 0x000414, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Time_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Distance_1) == 0x000418, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Distance_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Location_1) == 0x00041C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Location_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_ImpactPoint_1) == 0x000428, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_ImpactPoint_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_Normal_1) == 0x000434, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_Normal_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_ImpactNormal_1) == 0x000440, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_ImpactNormal_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_PhysMat_1) == 0x000450, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_PhysMat_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitActor_1) == 0x000458, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitActor_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitComponent_1) == 0x000460, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitComponent_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitBoneName_1) == 0x000468, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitBoneName_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_HitItem_1) == 0x000470, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_HitItem_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_FaceIndex_1) == 0x000474, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_FaceIndex_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_TraceStart_1) == 0x000478, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_TraceStart_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BreakHitResult_TraceEnd_1) == 0x000484, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BreakHitResult_TraceEnd_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_SpawnEmitterAtLocation_ReturnValue_1) == 0x000490, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_SpawnEmitterAtLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsServer_ReturnValue_1) == 0x000498, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsValid_ReturnValue_5) == 0x000499, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00049A, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, K2Node_CustomEvent_FortPickup) == 0x0004A0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::K2Node_CustomEvent_FortPickup' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetSquaredDistanceTo_ReturnValue) == 0x0004A8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetSquaredDistanceTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetAttachParentActor_ReturnValue) == 0x0004B0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetAttachParentActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_LessEqual_FloatFloat_ReturnValue) == 0x0004B8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_LessEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_NotEqual_ObjectObject_ReturnValue) == 0x0004B9, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_NotEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsDedicatedServer_ReturnValue) == 0x0004BA, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BooleanAND_ReturnValue_2) == 0x0004BB, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BooleanAND_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsServer_ReturnValue_2) == 0x0004BC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsServer_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetInstigator_ReturnValue_2) == 0x0004C0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetInstigator_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GetSquaredDistanceTo_ReturnValue_1) == 0x0004C8, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GetSquaredDistanceTo_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_GreaterEqual_FloatFloat_ReturnValue) == 0x0004CC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_GreaterEqual_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_K2_GetActorLocation_ReturnValue_4) == 0x0004D0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_K2_GetActorLocation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BooleanAND_ReturnValue_3) == 0x0004DC, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BooleanAND_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_MakeTransform_ReturnValue) == 0x0004E0, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000510, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_HasAnyMatchingGameplayTags_ReturnValue) == 0x000518, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_HasAnyMatchingGameplayTags_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_FinishSpawningActor_ReturnValue) == 0x000520, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, Temp_bool_Has_Been_Initd_Variable) == 0x000528, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsServer_ReturnValue_3) == 0x000529, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsServer_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, Temp_bool_Variable) == 0x00052A, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_IsServer_ReturnValue_4) == 0x00052B, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_IsServer_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost, CallFunc_HasInfiniteAmmo_ReturnValue) == 0x00052C, "Member 'Prj_Athena_HappyGhost_C_ExecuteUbergraph_Prj_Athena_HappyGhost::CallFunc_HasInfiniteAmmo_ReturnValue' has a wrong offset!");

// Function Prj_Athena_HappyGhost.Prj_Athena_HappyGhost_C.CustomPickupAttach
// 0x0008 (0x0008 - 0x0000)
struct Prj_Athena_HappyGhost_C_CustomPickupAttach final
{
public:
	class AFortPickup*                            FortPickup;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prj_Athena_HappyGhost_C_CustomPickupAttach) == 0x000008, "Wrong alignment on Prj_Athena_HappyGhost_C_CustomPickupAttach");
static_assert(sizeof(Prj_Athena_HappyGhost_C_CustomPickupAttach) == 0x000008, "Wrong size on Prj_Athena_HappyGhost_C_CustomPickupAttach");
static_assert(offsetof(Prj_Athena_HappyGhost_C_CustomPickupAttach, FortPickup) == 0x000000, "Member 'Prj_Athena_HappyGhost_C_CustomPickupAttach::FortPickup' has a wrong offset!");

// Function Prj_Athena_HappyGhost.Prj_Athena_HappyGhost_C.OnTouched
// 0x00A0 (0x00A0 - 0x0000)
struct Prj_Athena_HappyGhost_C_OnTouched final
{
public:
	class AActor*                                 OtherActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             HitResult;                                         // 0x0010(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          bIsOverlap;                                        // 0x009C(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(Prj_Athena_HappyGhost_C_OnTouched) == 0x000008, "Wrong alignment on Prj_Athena_HappyGhost_C_OnTouched");
static_assert(sizeof(Prj_Athena_HappyGhost_C_OnTouched) == 0x0000A0, "Wrong size on Prj_Athena_HappyGhost_C_OnTouched");
static_assert(offsetof(Prj_Athena_HappyGhost_C_OnTouched, OtherActor) == 0x000000, "Member 'Prj_Athena_HappyGhost_C_OnTouched::OtherActor' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_OnTouched, OtherComp) == 0x000008, "Member 'Prj_Athena_HappyGhost_C_OnTouched::OtherComp' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_OnTouched, HitResult) == 0x000010, "Member 'Prj_Athena_HappyGhost_C_OnTouched::HitResult' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_OnTouched, bIsOverlap) == 0x00009C, "Member 'Prj_Athena_HappyGhost_C_OnTouched::bIsOverlap' has a wrong offset!");

// Function Prj_Athena_HappyGhost.Prj_Athena_HappyGhost_C.ReceiveActorBeginOverlap
// 0x0008 (0x0008 - 0x0000)
struct Prj_Athena_HappyGhost_C_ReceiveActorBeginOverlap final
{
public:
	class AActor*                                 OtherActor;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Prj_Athena_HappyGhost_C_ReceiveActorBeginOverlap) == 0x000008, "Wrong alignment on Prj_Athena_HappyGhost_C_ReceiveActorBeginOverlap");
static_assert(sizeof(Prj_Athena_HappyGhost_C_ReceiveActorBeginOverlap) == 0x000008, "Wrong size on Prj_Athena_HappyGhost_C_ReceiveActorBeginOverlap");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveActorBeginOverlap, OtherActor) == 0x000000, "Member 'Prj_Athena_HappyGhost_C_ReceiveActorBeginOverlap::OtherActor' has a wrong offset!");

// Function Prj_Athena_HappyGhost.Prj_Athena_HappyGhost_C.ReceiveHit
// 0x00D0 (0x00D0 - 0x0000)
struct Prj_Athena_HappyGhost_C_ReceiveHit final
{
public:
	class UPrimitiveComponent*                    MyComp;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 Other;                                             // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    OtherComp;                                         // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bSelfMoved;                                        // 0x0018(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7BE1[0x3];                                     // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                HitLocation;                                       // 0x001C(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                HitNormal;                                         // 0x0028(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                NormalImpulse;                                     // 0x0034(0x000C)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             Hit;                                               // 0x0040(0x008C)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
};
static_assert(alignof(Prj_Athena_HappyGhost_C_ReceiveHit) == 0x000008, "Wrong alignment on Prj_Athena_HappyGhost_C_ReceiveHit");
static_assert(sizeof(Prj_Athena_HappyGhost_C_ReceiveHit) == 0x0000D0, "Wrong size on Prj_Athena_HappyGhost_C_ReceiveHit");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, MyComp) == 0x000000, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::MyComp' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, Other) == 0x000008, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::Other' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, OtherComp) == 0x000010, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::OtherComp' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, bSelfMoved) == 0x000018, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::bSelfMoved' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, HitLocation) == 0x00001C, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::HitLocation' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, HitNormal) == 0x000028, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::HitNormal' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, NormalImpulse) == 0x000034, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::NormalImpulse' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_ReceiveHit, Hit) == 0x000040, "Member 'Prj_Athena_HappyGhost_C_ReceiveHit::Hit' has a wrong offset!");

// Function Prj_Athena_HappyGhost.Prj_Athena_HappyGhost_C.SendQuestEvent
// 0x00B8 (0x00B8 - 0x0000)
struct Prj_Athena_HappyGhost_C_SendQuestEvent final
{
public:
	class AActor*                                 Hit_Actor;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayEventData                     K2Node_MakeStruct_GameplayEventData;               // 0x0008(0x00B0)()
};
static_assert(alignof(Prj_Athena_HappyGhost_C_SendQuestEvent) == 0x000008, "Wrong alignment on Prj_Athena_HappyGhost_C_SendQuestEvent");
static_assert(sizeof(Prj_Athena_HappyGhost_C_SendQuestEvent) == 0x0000B8, "Wrong size on Prj_Athena_HappyGhost_C_SendQuestEvent");
static_assert(offsetof(Prj_Athena_HappyGhost_C_SendQuestEvent, Hit_Actor) == 0x000000, "Member 'Prj_Athena_HappyGhost_C_SendQuestEvent::Hit_Actor' has a wrong offset!");
static_assert(offsetof(Prj_Athena_HappyGhost_C_SendQuestEvent, K2Node_MakeStruct_GameplayEventData) == 0x000008, "Member 'Prj_Athena_HappyGhost_C_SendQuestEvent::K2Node_MakeStruct_GameplayEventData' has a wrong offset!");

}

