#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Prop_CeilingTrack_01_S

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prop_CeilingTrack_01_S.Prop_CeilingTrack_01_S_C
// 0x0000 (0x0BC0 - 0x0BC0)
class AProp_CeilingTrack_01_S_C final : public ABuildingProp
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Prop_CeilingTrack_01_S_C">();
	}
	static class AProp_CeilingTrack_01_S_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_CeilingTrack_01_S_C>();
	}
};
static_assert(alignof(AProp_CeilingTrack_01_S_C) == 0x000008, "Wrong alignment on AProp_CeilingTrack_01_S_C");
static_assert(sizeof(AProp_CeilingTrack_01_S_C) == 0x000BC0, "Wrong size on AProp_CeilingTrack_01_S_C");

}

