#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SwimmingAnimLayerInterface

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass SwimmingAnimLayerInterface.SwimmingAnimLayerInterface_C
// 0x0000 (0x0028 - 0x0028)
class ISwimmingAnimLayerInterface_C final : public IAnimLayerInterface
{
public:
	void SwimmingLayer(const struct FPoseLink& MainPlayerAnimBP, struct FPoseLink* Param_SwimmingLayer);
	void SwimmingMovementAdditiveLayerPose(const struct FPoseLink& PassThroughSwimmingMovementAdditive, struct FPoseLink* Param_SwimmingMovementAdditiveLayerPose);
	void SwimmingSprintLayer(const struct FPoseLink& PassThroughSwimmingSprint, bool IsHidingInPropLayer, struct FPoseLink* Param_SwimmingSprintLayer);
	void SwimmingUpperBodyPoseTargetingLayer(const struct FPoseLink& PassThroughSwimmingUpperBodyPoseTargeting, struct FPoseLink* Param_SwimmingUpperBodyPoseTargetingLayer);
	void SwimmingUpperBodyPoseNonTargetingLayer(const struct FPoseLink& PassThroughSwimmingUpperBodyPoseNonTargeting, struct FPoseLink* Param_SwimmingUpperBodyPoseNonTargetingLayer);
	void SwimmingLowerBodyLayer(const struct FPoseLink& UpperBody_Cache, const struct FPoseLink& PreUpperBodySlot_Cache, const struct FPoseLink& PassThroughSwimmingLowerBody, struct FPoseLink* Param_SwimmingLowerBodyLayer);
	void SwimmingAdditiveLayer(const struct FPoseLink& IdleAdditive_Cache, const struct FPoseLink& MovementAdditiveLayerPose_Cache, const struct FPoseLink& FullBody, float PlayMeleeAttackAOLayer, float DisableArmsHeadAdditiveCurveAlphaLayer, float DisableIKRootAdditiveCurveAlphaLayer, float LocomotionAdditiveAlphaLayer, float MainInstanceAdditiveLayerAlpha, const struct FPoseLink& UpperAndLowerBody_Cache, const struct FPoseLink& SprintingPose_PostMask_Cache, struct FPoseLink* Param_SwimmingAdditiveLayer);
	void SwimmingFullBodyAdditiveLayer(const struct FPoseLink& PassThroughFullBodyAdditive, struct FPoseLink* Param_SwimmingFullBodyAdditiveLayer);
	void SwimmingDiveJumpingLayer(const struct FPoseLink& PassThroughSwimmingDiveJumping, bool IsHidingInPropLayer2, float MainInstanceDiveJumpLayerAlpha, EFortPlayerAnimBodyType AnimBodyTypePassThrough, struct FPoseLink* Param_SwimmingDiveJumpingLayer);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SwimmingAnimLayerInterface_C">();
	}
	static class ISwimmingAnimLayerInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ISwimmingAnimLayerInterface_C>();
	}
};
static_assert(alignof(ISwimmingAnimLayerInterface_C) == 0x000008, "Wrong alignment on ISwimmingAnimLayerInterface_C");
static_assert(sizeof(ISwimmingAnimLayerInterface_C) == 0x000028, "Wrong size on ISwimmingAnimLayerInterface_C");

}

