#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TabMouseAndKeyboardOptions_New

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TabMouseAndKeyboardOptions_New.TabMouseAndKeyboardOptions_New_C
// 0x0008 (0x0328 - 0x0320)
class UTabMouseAndKeyboardOptions_New_C final : public UFortTabMouseAndKeyboardOptions_TempNew
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0320(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_TabMouseAndKeyboardOptions_New(int32 EntryPoint);
	void CenterOnTab();
	void SettingValueChanged(float Value);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TabMouseAndKeyboardOptions_New_C">();
	}
	static class UTabMouseAndKeyboardOptions_New_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTabMouseAndKeyboardOptions_New_C>();
	}
};
static_assert(alignof(UTabMouseAndKeyboardOptions_New_C) == 0x000008, "Wrong alignment on UTabMouseAndKeyboardOptions_New_C");
static_assert(sizeof(UTabMouseAndKeyboardOptions_New_C) == 0x000328, "Wrong size on UTabMouseAndKeyboardOptions_New_C");
static_assert(offsetof(UTabMouseAndKeyboardOptions_New_C, UberGraphFrame) == 0x000320, "Member 'UTabMouseAndKeyboardOptions_New_C::UberGraphFrame' has a wrong offset!");

}

