#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyleMinusComMinussmall10_shadow

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Com-small10_shadow.TextStyle-Com-small10_shadow_C
// 0x0000 (0x0148 - 0x0148)
class UTextStyleMinusComMinussmall10_shadow_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-Com-small10_shadow_C">();
	}
	static class UTextStyleMinusComMinussmall10_shadow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyleMinusComMinussmall10_shadow_C>();
	}
};
static_assert(alignof(UTextStyleMinusComMinussmall10_shadow_C) == 0x000008, "Wrong alignment on UTextStyleMinusComMinussmall10_shadow_C");
static_assert(sizeof(UTextStyleMinusComMinussmall10_shadow_C) == 0x000148, "Wrong size on UTextStyleMinusComMinussmall10_shadow_C");

}

