#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Torso_Only_CtrlRig

#include "Basic.hpp"

#include "ControlRig_classes.hpp"


namespace SDK
{

// ControlRigBlueprintGeneratedClass Torso_Only_CtrlRig.Torso_Only_CtrlRig_C
// 0x0000 (0x0360 - 0x0360)
class UTorso_Only_CtrlRig_C final : public UControlRig
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Torso_Only_CtrlRig_C">();
	}
	static class UTorso_Only_CtrlRig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTorso_Only_CtrlRig_C>();
	}
};
static_assert(alignof(UTorso_Only_CtrlRig_C) == 0x000008, "Wrong alignment on UTorso_Only_CtrlRig_C");
static_assert(sizeof(UTorso_Only_CtrlRig_C) == 0x000360, "Wrong size on UTorso_Only_CtrlRig_C");

}

