#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Western_Wall_Trim_006

#include "Basic.hpp"

#include "Parent_BuildingPropWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Western_Wall_Trim_006.Western_Wall_Trim_006_C
// 0x0000 (0x0BD8 - 0x0BD8)
class AWestern_Wall_Trim_006_C final : public AParent_BuildingPropWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Western_Wall_Trim_006_C">();
	}
	static class AWestern_Wall_Trim_006_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWestern_Wall_Trim_006_C>();
	}
};
static_assert(alignof(AWestern_Wall_Trim_006_C) == 0x000008, "Wrong alignment on AWestern_Wall_Trim_006_C");
static_assert(sizeof(AWestern_Wall_Trim_006_C) == 0x000BD8, "Wrong size on AWestern_Wall_Trim_006_C");

}

